#define VIAL_KEYBOARD_UID {0x72, 0xD1, 0xB2, 0x31, 0x83, 0x84, 0x13, 0xDE}

#define WEAR_LEVELING_LOGICAL_SIZE (8 * 1024)
#define WEAR_LEVELING_BACKING_SIZE (WEAR_LEVELING_LOGICAL_SIZE * 2)

#define DYNAMIC_KEYMAP_LAYER_COUNT 16

#define TAPPING_TERM 400
#define RETRO_TAPPING

/* autoshift settings  */
#define AUTO_SHIFT_TIMEOUT 450
#define AUTO_SHIFT_TIMEOUT_PER_KEY
#define NO_AUTO_SHIFT_TAB
#define RETRO_SHIFT 1000
